name: CI/CD Pipeline - STV Voting System

# Controla quando o workflow será executado
on:
  # Aciona o workflow em eventos de push ou pull request, mas apenas para o branch "main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Permite executar este workflow manualmente a partir da aba Actions
  workflow_dispatch:

jobs:
  # Primeiro job: Teste da aplicação
  test:
    # O tipo de runner que o job vai usar
    runs-on: ubuntu-latest

    # Passos que serão executados como parte do job
    steps:
      # Faz o checkout do repositório para o workspace do GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura o Node.js para rodar os testes do Hardhat
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Instala as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Roda os testes usando o framework Hardhat
      - name: Run Hardhat tests
        run: npm run test

      # Verifica se os testes foram bem-sucedidos
      - name: Check test results
        run: echo "Testes concluídos com sucesso!"

  # Segundo job: Deploy da aplicação
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura o Node.js novamente para o processo de deploy
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Instala as dependências novamente
      - name: Install dependencies for deployment
        run: npm install

      # Executa o script de deploy usando Hardhat
      - name: Deploy contract to network
        run: npm run deploy
