# Workflow de exemplo para construir e implantar um site Next.js no Vercel
#
# Para começar com Next.js, veja: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Vercel

on:
  # Executa em pushes direcionados ao branch padrão
  push:
    branches: ["main"]

  # Permite executar este workflow manualmente na aba de Actions
  workflow_dispatch:

# Define as permissões do GITHUB_TOKEN para permitir a implantação no Vercel
permissions:
  contents: read
  deployments: write

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Detectar gerenciador de pacotes
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Não foi possível determinar o gerenciador de pacotes"
            exit 1
          fi
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Instalar dependências
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
      - name: Build com Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build
      - name: Adicionar variáveis de ambiente do Vercel
        run: |
          echo "VERCEL_TOKEN=${{ 74KT7ALYVDCSYmqWM6NV6iJx }}" >> $GITHUB_ENV
          echo "VERCEL_ORG_ID=${{ team_IQgDjmAuyFa7piKIKcG6xVA5 }}" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=${{ prj_Fn66enBNvjAuNY90QfGce8mNrMeZ }}" >> $GITHUB_ENV

  # Job de deployment
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para Vercel
        run: |
          npx vercel --token ${{ WSwlMKUHo5iFlbSzIjptbghr }} --prod
